#!/bin/sh

# Use this to run 'generate-lda' with a '--filter-regex' that filters for
# "colored" spans, i.e. spans mentioning the terms "contraband", "slave",
# "negro", "colord", "freedman/freedmen", or certain expressions involving
# the word "black". Example of how to run:
#
#
# ./filter-colored-generate-lda --input wotr-spans.may-18-715pm --output wotr.may-18-715pm.colored.combined.input

./generate-lda --filter-regex '([Cc]ontraband|[Ss]lave|[Nn]egro|[Cc]olored|[Ff]reedm[ae]n|\b(blacks|[Ww]hite (and|or|nor) black|[Bb]lack (and|or|nor) white|[Ff]ree black|[Bb]lack (m[ae]n|wom[ae]n|child(ren)?|persons?|people|citizens?|masses|populations?|males?|boys?|labor|forces?|soldiers?|sailors?|regiments?|brigades?|troops?|infantry|militia|recruits?|gunners?|races?|refugees?|[Rr]epublicans?))\b)' "$@"
