#!/usr/bin/env python

import argparse
import re
import os
import text
import sys

parser = argparse.ArgumentParser(description='Generate LDA data for use with Mallet for some or all of given spans')
parser.add_argument('--filter-regex',
    help="Regex to filter spans.")
parser.add_argument('--input', required=True,
    help="Directory containing input files, or TextDB data file.")
parser.add_argument('--output',
    help="File to output LDA data to.")
parser.add_argument('--textdb', action="store_true",
    help="File in '--input' is a TextDB data file.")

args = parser.parse_args()

def process_wotr_files(of):
  for fn in os.listdir(args.input):
    print fn,
    text = open(os.path.join(args.input, fn)).read()
    num_handled_spans = 0
    spanno = 1
    for span in re.finditer(r'^-----+ BEGIN SPAN -----+$(.*?)^-----+ END SPAN -----+$', text, re.M | re.S):
      spantext = span.group(1)
      if not args.filter_regex or re.search(args.filter_regex, spantext):
        if of:
          of.write("%s.%s span %s\n" % (fn, spanno, spantext.strip().replace("\n", " ")))
        num_handled_spans += 1
      spanno += 1
    print "%s spans" % num_handled_spans

def process_textdb(of):
  schemafn = re.sub(r'^(.*)-data.txt(\.bz2)?$', r'\1', args.input)
  with open(schemafn) as schemafile:
    schemafields = next(schemafile)
  titlefield = schemafields.index('title')
  textfield = schemafields.index('text')

  if args.spans.endswith(".bz2"):
    spanfile = bz2.BZ2File(args.spans)
  else:
    spanfile = open(args.spans)

  num_handled_spans = 0
  for line in spanfile:
    if line.endswith('\n'):
      line = line[0:-1]
    fields = re.split("\t", line)
    spantext = (fields[textfield].replace("%0C", "\f").replace("%0D", "\r").
        replace("%0A", "\n").replace("%09", "\t").replace("%25", "%"))
    title = fields[titlefield]
    if not args.filter_regex or re.search(args.filter_regex, spantext):
      if of:
        of.write("%s span %s\n" % (title, spantext.strip().replace("\n", " ")))
      num_handled_spans += 1
  print "%s spans" % num_handled_spans

if args.textdb:
  procfn = process_textdb
else:
  procfn = process_wotr_files
if args.output:
  with open(args.output, "w") as of:
    procfn(of)
else:
  procfn(None)
